# Car Accident Severity Resulting in Fatalities #

## Introduction ##
'Since March 2020 the corona-virus pandemic a _shelter-in-place_ order has minimized vehicles on thr roadways.  Instead of the minimal vehicles on the roadways, providing a safer  enviroment and insurance claim activity [cost], the opposite has occured.  Between the National Highway Safety Admininstration (NHTSA) and Insurance Service Office (ISO), car accident severity is rising at an alarming pace.  How can this be correct!  Basic logical deduction: _Less vehicle traffic produces less traffic accidents, especially server accidents._

In today's news, one health spokeman announced that the corona-virus pandemic's United States _shelter-in-place_ strategy could last until the end of 2021!  This is a study using Machine Learning alogrithms to __predict__ 07/2020 to 06/2021 fatalities based on a prior 12 months of data.'

## Business Problem ##
'Annually, insurance companies perform a _rate-making_ process to set premium rates, also known as _insurance pricing_. A rate is the price unit of insurance for each exposure unit. Vehicle coverage as property and casualty insurance, the exposure unit is typically equal to \\$100 of property value, and liability is measured in \\$1000 units. This study is focused on liability.'

'Key _rate-making_ personnel are insurance underwriters and actuaries.'

'The _rate-making_ process workflow is as follows:
> 1. Identify the car accidents with fatalities data points
> 2. Categorize data points: car fatalities, timing and volume
> 3. Select Machine Learning Predictive Alogritm
> 4. Perform Parameter Tuning and Averaging
> 5. Create 2021 rates

 



## Data Section ##

### Resources ###

> __NHTSA: Early Estimates of Motoer Vehicle Fatalities, 2019__
>> - Fatalities Quarterly data with percentage of change
>> - 10-Regional counts and percentage of change<br>

> __Injury Facts NSC: Traffic Volume/Averages__
>> - Volume of Miles Driven
>> - Number deaths
>> - Number of Fatal Crashes<br>

> __NSC January 2019 and June 2020__
>> - Total U.S. Motor Vehicle Deaths
>>>  - comparisons for 2020, 2019, 2018
>>>  - percentage change
>>>>   - 2019 to 2020
>>>>   - 2018 to 2020

Using supervised learning to identify data patterns in creating __2021__ fatalities predictions based on above mentioned analysis.

## Methodology ##

Machine Learning Pipeline: (numbered in processing order)
> 1. preprocessing data
> 2. selection of feature(s)
> 3. extraction of feature(s)
> 4. train - test - split
> 5. algorithm selection
> 6. fit the models
> 7. tunr the parameters
> 8. _prediction_
> 9. evaluation



#### Source Data ####
'To coincide with existing __Car Accident Fatality__ findings only NSC monthly numbers are analyzed.  Data is compiled in monthly Excel spreadsheets.  Consider the spreadsheets as source data.  The source data populate *accident* Pandas dataframe. Accident dataframe contents '

#### Feature Extraction ####
Comparing data from 2009 versus 2020  
> Identify trends and/or patterns
> Vehicle Miles Traveled (VMT)
> Fatality Rate per 100 million VMT

#### Machine Learning Model ###
'Supervised Learning algoritms will afford using the patterns in the traffic fatalities data to make predictions. Random Forests Algorithm afford prediction, analysis and results. 

__Justification:__
> Prediction for *Probabilites, Categorical Outcomes and Continous Outcomes*
> Analysis is *Simple to Use*
> Results are *Highly Accurate*

__Note for Model Tuning Parameters strategies:__
> Adjusting all the parameters of the Decision Tree
> Changing the Number of Trees
> Number of variables to select at the split

## Results ##
Use current report analysis are benchmark and provide findings for consideration to *Rate-making* process. Fatalities have a strong influence of liability cost considerations and insurer exposture. 

## Discussion ##

## Conclusion ##

## Report Analysis

In [1]:
# Preprocessing

#### The Study ####
>1. Prepare data (3 datasets featuring years, months, miles travelled and fatalities).
>2. Applying a different algorithm to each dataset.
>3. Tune algorithms to optimize the models.
>4. Evaluate models based on their accuracy.

In [33]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [34]:
# Dataset 1: Fatalities Percentage Change Annually by Quarter  

df = pd.read_csv('Percentage_change.csv',delimiter=';')
df.head()

Year    1Q   2Q   3Q    4Q  Annual
0  2009 -10.7 -4.9 -8.5 -13.9    -9.5
1  2010 -10.6 -5.0  1.3   3.0    -2.6
2  2011  -0.4 -3.5 -2.6   0.5    -1.6
3  2012  11.8  4.7  2.1  -0.7     4.0
4  2013  -4.7 -4.7 -1.6   0.2    -2.6

In [35]:
# Selection of Features

df.columns


Index(['Year', '1Q', '2Q', '3Q', '4Q', 'Annual'], dtype='object')

In [37]:
# Feature Set

X = df[['Year', '1Q','2Q','3Q','4Q', 'Annual']].values 
#X=df.to_numpy()
X[0:5]

array([[ 2.009e+03, -1.070e+01, -4.900e+00, -8.500e+00, -1.390e+01,
        -9.500e+00],
       [ 2.010e+03, -1.060e+01, -5.000e+00,  1.300e+00,  3.000e+00,
        -2.600e+00],
       [ 2.011e+03, -4.000e-01, -3.500e+00, -2.600e+00,  5.000e-01,
        -1.600e+00],
       [ 2.012e+03,  1.180e+01,  4.700e+00,  2.100e+00, -7.000e-01,
         4.000e+00],
       [ 2.013e+03, -4.700e+00, -4.700e+00, -1.600e+00,  2.000e-01,
        -2.600e+00]])

In [38]:
# Labels

y = df['Annual'].values
y[0:5]

array([-9.5, -2.6, -1.6,  4. , -2.6])

In [ ]:
# Normalize Data

In [39]:
# Data Standardization to give zero mean and unit variance

X = preprocessing.StandardScaler().fit(X).transform(X.astype(float))
X[0:5]

array([[-1.58113883e+00, -1.39998009e+00, -1.01572418e+00,
        -1.83879863e+00, -2.49511529e+00, -1.97531687e+00],
       [-1.26491106e+00, -1.38638805e+00, -1.03696556e+00,
         2.74447556e-01,  5.84844421e-01, -5.06888365e-01],
       [-9.48683298e-01, -6.79058793e-17, -7.18344855e-01,
        -5.66538170e-01,  1.29229079e-01, -2.94072639e-01],
       [-6.32455532e-01,  1.65822884e+00,  1.02344831e+00,
         4.46957449e-01, -8.94662853e-02,  8.97695425e-01],
       [-3.16227766e-01, -5.84457706e-01, -9.73241416e-01,
        -3.50900804e-01,  7.45552378e-02, -5.06888365e-01]])

In [41]:
# Train-Split-Test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
print('Train set:', X_train.shape, y_train.shape)
print('Test set:', X_test.shape, y_test.shape)


Train set: (8, 6) (8,)
Test set: (3, 6) (3,)


In [3]:
# Dataset 2: Fatality Rate per 100 Million Vehicle Miles Traveled

df1=pd.read_csv('Fatality_Rate.csv',delimiter=';')
df1.head()

Year    1Q    2Q    3Q    4Q  Annual
0  2009  1.09  1.16  1.17  1.12    1.15
1  2010  0.98  1.09  1.18  1.14    1.11
2  2011  0.98  1.09  1.18  1.17    1.10
3  2012  1.08  1.12  1.21  1.16    1.14
4  2013  1.04  1.07  1.17  1.15    1.10

In [13]:
df1.columns

Index(['Year', '1Q', '2Q', '3Q', '4Q', 'Annual'], dtype='object')

In [9]:
# Dataset 3: Vehicle Miles Travelled Monthly Total

df2=pd.read_csv('VMT09to18.csv',delimiter=',')

new_order=[1,0,2,3]
df3=df2[df2.columns[new_order]]
df3.head()

Year Month      VMT Seasonally Adjusted VMT (2009 to present)
0  2009   Jan  225,529                                   245,487
1  2009   Feb  217,643                                   249,041
2  2009   Mar  249,741                                   245,286
3  2009   Apr  251,374                                   247,503
4  2009   May  258,276                                   246,975

In [14]:
df3.columns

Index(['Year', 'Month', 'VMT', 'Seasonally Adjusted VMT (2009 to present)'], dtype='object')

In [ ]:
# Algorithm selection

In [ ]:
# Fit models

In [ ]:
# Tune parameters

In [ ]:
# Prediction

In [ ]:
# Evaluation